### ISSUE TITLE
Arbitrary input image size

### ISSUE THREAD

**Issue by moshanATucsd** [xingyizhou/StarMap#4]
Hi, the network has to crop the input image to 256x256, and I am wondering whether we could feed arbitrary size? Global average pooling might be useful, but I am wondering whether you have any specific suggestions?

**Comment by xingyizhou** [comment]
Hi, 
  I think the current architecture directly support feeding a larger image for testing, since it is fully convolutional. You can also change input_res and ouput_res to train on your own resolution if you want, however my preliminary experiments told me it doesn't give much performance gain if not changing the hyper-parameters. Maybe considering also increase ref.hmGauss if you want to try larger resolution. Thanks!

**Comment by moshanATucsd** [comment]
I see, then in the demo, why do we always have to crop the image to a specific size? Why can't we just feed any image directly? 

```
img = Crop(img, c, s, 0, ref.inputRes).astype(np.float32).transpose(2, 0, 1) / 256.
```

**Comment by xingyizhou** [comment]
I haven't tested with different size. I did so for a consistency with the benchmark evaluation.
